// header/src/App.svelte
<script>
  import Header from "./Header.svelte";
  import * as Footer from 'footer/Footer'
  import Button from 'button/Button'

const mountSvelteComponent = (node, comp) => new comp({target: node})

</script>
<Header />
<div class="container">
  <div>Name: header</div>
  <div>Framework: svelte</div>
  <div>Language: JavaScript</div>
  <div>CSS: Empty CSS</div>
</div>
<div use:Footer.mount></div>

<div use:mountSvelteComponent={Button}></div>

// consumer/src/App.tsx
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import Header from "header/Header";
import Footer from "footer/Footer";

import "./index.css";

const App = () => {
  return (
    <>
      <div ref={(el) => new Header({ target: el })}></div>
      <div className="container">
        <div>Name: consumer</div>
        <div>Framework: react</div>
        <div>Language: TypeScript</div>
        <div>CSS: Empty CSS</div>
      </div>
      <Footer />
    </>
  );
};
ReactDOM.render(<App />, document.getElementById("app"));
